import { Restaurant, Notice, Booking, ThemeConfig, SeoConfig } from './types';

export const INITIAL_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-1',
    name: '임방식당',
    category: '한식 / 찌개 / 볶음류',
    description: '정갈한 밑반찬과 깊은 국물의 찌개, 볶음류 맛집',
    voucherOnly: false,
    tel: '02-555-1284',
    iconName: 'Utensils',
    menus: [
      { id: 'ib-1', name: '묵은지 김치찌개(2인이상)', price: 10000 },
      { id: 'ib-2', name: '옛날육개장', price: 10000 },
      { id: 'ib-3', name: '육개장칼국수', price: 10000 },
      { id: 'ib-4', name: '사골떡만둣국', price: 10000 },
      { id: 'ib-5', name: '뚝배기 김치찌개', price: 10000 },
      { id: 'ib-6', name: '한우차돌 된장찌개', price: 10000 },
      { id: 'ib-7', name: '냉면', price: 10000 },
      { id: 'ib-8', name: '사골칼국수', price: 10000 },
      { id: 'ib-9', name: '제육볶음', price: 10000 },
      { id: 'ib-10', name: '해물된장찌개 전골', price: 10000 },
      { id: 'ib-11', name: '코다리찜', price: 10000 },
    ],
  },
  {
    id: 'rest-2',
    name: '칭마레이',
    category: '중식',
    description: '정통 중화요리 전문점 (위 3개 메뉴 식권 식사 가능)',
    voucherOnly: false,
    voucherNotice: '위 세 메뉴만 식권으로 식사 가능하며, 이외 메뉴는 추가금액 발생합니다.',
    tel: '02-555-8930',
    iconName: 'Soup',
    menus: [
      { id: 'cm-1', name: '짜장면', price: 10000 },
      { id: 'cm-2', name: '짬뽕', price: 10000 },
      { id: 'cm-3', name: '새우볶음밥', price: 10000 },
    ],
  },
  {
    id: 'rest-3',
    name: '고릴라쿡',
    category: '분식 / 덮밥 / 찌개 / 돈까스',
    description: '덮밥, 찌개, 돈까스, 분식 등 다채로운 메뉴를 즐길 수 있는 식당',
    voucherOnly: false,
    tel: '02-555-4421',
    iconName: 'Sandwich',
    menus: [
      { id: 'gc-1', name: '제육덮밥', price: 10000 },
      { id: 'gc-2', name: '갈비양념덮밥', price: 10000 },
      { id: 'gc-3', name: '우삼겹 덮밥', price: 10000 },
      { id: 'gc-4', name: '스팸마요덮밥', price: 10000 },
      { id: 'gc-5', name: '참치마요덮밥', price: 10000 },
      { id: 'gc-6', name: '돼지김치찌개', price: 10000 },
      { id: 'gc-7', name: '냉소바', price: 10000 },
      { id: 'gc-8', name: '김치볶음밥', price: 10000 },
      { id: 'gc-9', name: '새우볶음밥', price: 10000 },
      { id: 'gc-10', name: '버터계란 볶음밥', price: 10000 },
      { id: 'gc-11', name: '오징어덮밥', price: 10000 },
      { id: 'gc-12', name: '순두부찌개', price: 10000 },
      { id: 'gc-13', name: '된장찌개', price: 10000 },
      { id: 'gc-14', name: '참치 김치찌개', price: 10000 },
      { id: 'gc-15', name: '뚝배기 불고기', price: 10000 },
      { id: 'gc-16', name: '라면', price: 10000 },
      { id: 'gc-17', name: '떡라면', price: 10000 },
      { id: 'gc-18', name: '치즈라면', price: 10000 },
      { id: 'gc-19', name: '만두라면', price: 10000 },
      { id: 'gc-20', name: '해장라면', price: 10000 },
      { id: 'gc-21', name: '김치우동', price: 10000 },
      { id: 'gc-22', name: '우동', price: 10000 },
      { id: 'gc-23', name: '떡볶이', price: 10000 },
      { id: 'gc-24', name: '라볶이', price: 10000 },
      { id: 'gc-25', name: '쫄면', price: 10000 },
      { id: 'gc-26', name: '돈까스', price: 10000 },
      { id: 'gc-27', name: '치즈돈까스', price: 10000 },
      { id: 'gc-28', name: '고구마돈까스', price: 10000 },
      { id: 'gc-29', name: '왕돈까스', price: 10000 },
      { id: 'gc-30', name: '일반김밥', price: 10000 },
      { id: 'gc-31', name: '참치김밥', price: 10000 },
      { id: 'gc-32', name: '치즈김밥', price: 10000 },
    ],
  },
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'notice-1',
    title: '📢 [공지] 오늘 점심 신청 마감 및 식대 지원 안내',
    content: '금일 점심 신청은 식당 준비 및 주문 집계를 위해 오전 10:30에 마감됩니다. 인당 10,000원 기준을 준수해 주시기 바랍니다.',
    isPinned: true,
    date: '오늘 09:30',
    type: 'notice',
  },
  {
    id: 'notice-2',
    title: '💡 [점심 안내] 식당별 이동 및 예약 준수 안내',
    content: '각 조별 대표자께서는 11:45까지 식당으로 이동해 주시기 바라며, 변동 사항이 있을 경우 대시보드를 통해 확인해 주세요.',
    isPinned: false,
    date: '오늘 09:50',
    type: 'info',
  },
  {
    id: 'notice-3',
    title: '🚗 [안내] 이동 매너 및 변경 사항 접수',
    content: '식당 사전 예약 후 불가피하게 인원 변동이나 취소가 발생하는 경우 실시간 대시보드에서 수정 또는 관리자에게 즉시 알려주세요.',
    isPinned: false,
    date: '오늘 10:45',
    type: 'info',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'book-1',
    representativeName: '홍*동',
    rawName: '홍길동',
    headcount: 4,
    companions: ['김*수', '이*희', '박*민'],
    rawCompanions: ['김철수', '이영희', '박지민'],
    memo: '김치찌개 덜 맵게 부탁드립니다!',
    restaurantId: 'rest-1',
    restaurantName: '임방식당',
    items: [
      { menuItemId: 'ib-1', name: '묵은지 김치찌개(2인이상)', price: 10000, quantity: 2 },
      { menuItemId: 'ib-9', name: '제육볶음', price: 10000, quantity: 2 },
    ],
    totalAmount: 40000,
    totalBudget: 40000,
    difference: 0, // exactly on budget
    agreedToPolicy: true,
    createdAt: '10:42',
    status: '접수완료',
  },
  {
    id: 'book-2',
    representativeName: '이*수',
    rawName: '이진수',
    headcount: 3,
    companions: ['최*아', '강*우'],
    rawCompanions: ['최수아', '강현우'],
    memo: '11시 55분경 도착 예정입니다.',
    restaurantId: 'rest-2',
    restaurantName: '칭마레이',
    items: [
      { menuItemId: 'cm-1', name: '짜장면', price: 10000, quantity: 1 },
      { menuItemId: 'cm-2', name: '짬뽕', price: 10000, quantity: 1 },
      { menuItemId: 'cm-3', name: '새우볶음밥', price: 10000, quantity: 1 },
    ],
    totalAmount: 30000,
    totalBudget: 30000,
    difference: 0,
    agreedToPolicy: true,
    createdAt: '10:55',
    status: '접수완료',
  },
  {
    id: 'book-3',
    representativeName: '박*민',
    rawName: '박상민',
    headcount: 2,
    companions: ['정*은'],
    rawCompanions: ['정다은'],
    memo: '돈까스 소스 따로 부탁드려요.',
    restaurantId: 'rest-3',
    restaurantName: '고릴라쿡',
    items: [
      { menuItemId: 'gc-29', name: '왕돈까스', price: 10000, quantity: 1 },
      { menuItemId: 'gc-1', name: '제육덮밥', price: 10000, quantity: 1 },
    ],
    totalAmount: 20000,
    totalBudget: 20000,
    difference: 0,
    agreedToPolicy: true,
    createdAt: '11:05',
    status: '식당이동중',
  },
];

export const DEFAULT_THEME_CONFIG: ThemeConfig = {
  primaryColor: '#2C2B70',
  secondaryColor: '#C6C4C3',
  accentColor: '#3b82f6',
  bgColor: '#f8fafc',
  font: 'Noto Sans KR',
  isDark: false,
  siteTitle: '신세계 Future & Dream Academy',
  siteSubtitle: '교육생 실시간 점심 예약 & 식대 관리 시스템',
  budgetPerPerson: 10000,
  deadlineTime: '10:30',
  adminPassword: '9707',
};

export const DEFAULT_SEO_CONFIG: SeoConfig = {
  metaTitle: '신세계 Future & Dream Academy - 교육생 실시간 점심 예약 & 식대 관리 시스템',
  metaDescription: '신세계 Future & Dream Academy 교육생 실시간 점심 예약 & 식대 관리 시스템',
  keywords: '신세계, Future & Dream Academy, 퓨쳐앤드림아카데미, 점심신청, 교육생식대, 식대계산기, 식당예약, 관리자대시보드, 임방식당, 칭마레이, 고릴라쿡',
};
